---
swagger: '2.0'
info:
  version: 1.0.0
  title: API
basePath: "/"
paths:
  "/":
    get:
      description: Endpoint raiz
      responses:
        '200':
          description: OK
  "/pessoas":
    post:
      description: Criar pessoa
      responses:
        '200':
          description: OK
    get:
      description: Listar pessoas
      responses:
        '200':
          description: OK
  "/pessoas/{id}":
    get:
      description: Obter pessoa por ID
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
    patch:
      description: Atualizar pessoa
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
    delete:
      description: Excluir pessoa
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
  "/cidades/{id}":
    get:
      description: Obter cidades por ID
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
    patch:
      description: Atualizar cidades
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
    delete:
      description: Excluir cidades
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK